---
HOSTS:
  debian-9-64-1:
    platform: debian-9-amd64
    hypervisor: docker
    image: debian:9
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'echo deb http://ftp.debian.org/debian stretch-backports main >> /etc/apt/sources.list'
      - 'apt-get update && apt-get install -y cron locales-all net-tools wget'
      - 'rm -f /usr/sbin/policy-rc.d'
      - 'systemctl mask getty@tty1.service getty-static.service'
CONFIG:
  trace_limit: 200
  masterless: true
...
